import React, { useState, useEffect } from 'react';
import { Save, Check, Loader2, WifiOff } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { useSchool } from '@/components/school/SchoolProvider';
const statuses = ['Present', 'Absent', 'Late', 'Excused'];
const styles = { Present: 'bg-[#e6efdf] text-[#628347] border-[#cddcbb]', Absent: 'bg-[#faeae3] text-[#b47b64] border-[#ecccb9]', Late: 'bg-[#faf1d8] text-[#ad9253] border-[#e9d8aa]', Excused: 'bg-[#eaeaf4] text-[#8888a5] border-[#d3d3e4]' };
export default function AttendanceRegister({ classId, date }) {
 const { data, school, save, isDemo, user } = useSchool(); const existing = data.attendance.find(a => a.class_id === classId && a.date === date); const students = data.students.filter(s => s.class_id === classId);
 const [values, setValues] = useState(Object.fromEntries((existing?.entries || []).map(e => [e.student_id, e.status]))); const [version, setVersion] = useState(existing?.updated_date); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false); const [online, setOnline] = useState(navigator.onLine);
 useEffect(() => { const sync = () => setOnline(navigator.onLine); window.addEventListener('online', sync); window.addEventListener('offline', sync); return () => { window.removeEventListener('online', sync); window.removeEventListener('offline', sync); }; }, []);
 const count = students.filter(s => values[s.id]).length;
 async function submit() { setBusy(true); setError(''); try { let record = existing; if (!isDemo) { const matches = await base44.entities.ClassAttendance.filter({ school_id: school.id, class_id: classId, date, created_by_id: user.id }); record = matches[0]; if (record && record.updated_date !== version) throw new Error('This register was changed in another session. Reopen this date to load the latest saved register before editing.'); } const result = await save('attendance', { class_id: classId, date, entries: students.map(s => ({ student_id: s.id, status: values[s.id] })) }, record?.id); setVersion(result.updated_date); setSaved(true); } catch (err) { setError(err.message || 'Not saved. Your entries remain on this page; reconnect and try again.'); } finally { setBusy(false); } }
 return <section className="panel p-0">{!online && <div className="flex items-center gap-2 bg-[#faf1d8] p-4 text-xs"><WifiOff size={15} />Offline — keep this page open. Entries are not saved until you reconnect and press Save.</div>}<div className="flex items-center justify-between gap-3 p-5"><div><h2 className="text-sm font-semibold">Class register</h2><p className="mt-1 text-[10px] text-[#8d9980]">{count} of {students.length} marked{existing ? ' · Saved register available' : ''}</p></div><button disabled={!students.length} className="action-secondary" onClick={() => { setValues(Object.fromEntries(students.map(s => [s.id, 'Present']))); setSaved(false); }}>Mark all present</button></div>{students.map(s => <div key={s.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-[#edf0e6] px-5 py-3.5"><span className="text-xs font-medium">{s.name}</span><div className="flex gap-1.5">{statuses.map(status => <button key={status} onClick={() => { setValues(v => ({ ...v, [s.id]: status })); setSaved(false); }} className={`rounded-md border px-2.5 py-2 text-[10px] transition-colors sm:px-4 ${values[s.id] === status ? styles[status] : 'border-[#e6eade] text-[#98a28b] hover:bg-[#f7f8f1]'}`}>{status}</button>)}</div></div>)}{!students.length && <p className="p-12 text-center text-xs text-[#8d9980]">No students in this class yet.</p>}<div className="flex flex-wrap items-center justify-between gap-3 border-t p-5"><p className="text-[10px] text-[#929d84]">Present and late count toward attendance. Excused absences remain recorded.</p><button className="action-primary" disabled={busy || !online || !students.length || count !== students.length || saved} onClick={submit}>{busy ? <Loader2 size={14} className="animate-spin" /> : saved ? <Check size={14} /> : <Save size={14} />}{saved ? 'Register saved' : 'Save register'}</button></div>{error && <p role="alert" className="px-5 pb-5 text-xs text-red-600">{error}</p>}</section>;
}