import React from 'react';
import RecordForm from '@/components/school/RecordForm';
import { useSchool } from '@/components/school/SchoolProvider';
import { learnerInsight, resultsFor } from '@/components/school/intelligence';
export default function InterventionForm({ student, plan, onClose }) {
 const { data, save } = useSchool(); const insight = learnerInsight(student, data);
 const matching = plan ? resultsFor(student.id, data.assessments).filter(r => r.subject === plan.subject && (!plan.topic || r.topic === plan.topic) && r.date > plan.start_date) : [];
 const fields = plan ? [{ key: 'followup_assessment', label: 'Recorded follow-up evidence', required: true, options: matching.map(r => ({ value: r.id, label: `${r.title} · ${r.date} · ${r.percentage}%` })) }, { key: 'outcome', label: 'Teacher outcome and next steps', type: 'textarea', required: true }] : [{ key: 'subject', label: 'Subject', required: true }, { key: 'topic', label: 'Topic' }, { key: 'issue', label: 'What needs support?', required: true }, { key: 'evidence', label: 'Recorded evidence', type: 'textarea', required: true }, { key: 'action', label: 'Teacher-approved action', type: 'textarea', required: true }, { key: 'owner', label: 'Responsible person', required: true }, { key: 'review_date', label: 'Review date', type: 'date', min: new Date().toISOString().slice(0, 10), required: true }, { key: 'parent_involvement', label: 'Parent involvement plan (not sent)', type: 'textarea' }];
 const initial = plan ? { outcome: '', followup_assessment: matching.at(-1)?.id || '' } : { subject: insight.latest?.subject || '', topic: insight.latest?.topic || '', issue: `${insight.latest?.topic || 'Learning'} support`, evidence: insight.evidence, action: `Consider two targeted ${insight.latest?.topic || 'subject'} practice sessions, followed by reassessment.`, owner: data.classes.find(c => c.id === student.class_id)?.teacher || '', review_date: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10), parent_involvement: '' };
 return <RecordForm title={plan ? `Review ${student.name}’s support` : `Support ${student.name}`} description={plan ? 'Choose an actual follow-up result. A changed score is evidence of progress, not proof of what caused it.' : 'A rule-based starting point, not an AI conclusion. Review the evidence and edit the action before saving.'} fields={fields} initial={initial} onClose={onClose} onSave={async values => { if (plan) { const result = matching.find(r => r.id === values.followup_assessment); if (!result) throw new Error('Record a follow-up assessment in this subject and topic after the support start date first.'); await save('interventions', { ...plan, status: 'Completed', followup_score: result.percentage, outcome: `${values.outcome}\nEvidence: ${result.title} (${result.date}), ${result.score}/${result.maximum}. Baseline ${plan.baseline ?? 'not recorded'}%; follow-up ${result.percentage}%.` }, plan.id); } else { const baselineResult = insight.results.filter(r => r.subject === values.subject && (!values.topic || r.topic === values.topic)).at(-1); if (!baselineResult) throw new Error('Choose a subject and topic with a recorded result so this plan has an evidence-based baseline.'); await save('interventions', { ...values, student_id: student.id, baseline: baselineResult.percentage, start_date: new Date().toISOString().slice(0, 10), status: 'Active' }); } }} />;
}