import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, BookOpen, Clock3, ArrowRight } from 'lucide-react';
import { useSchool } from '@/components/school/SchoolProvider';
import { average, displayPercent, percent } from '@/components/school/intelligence';
export default function OverviewActivity() {
 const { data } = useSchool(); const recent = [...data.assessments].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 3); const followups = data.interventions.filter(i => i.status === 'Active').sort((a, b) => (a.review_date || '').localeCompare(b.review_date || ''));
 return <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><section className="panel"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">Recently recorded</h2><Link to="/assessments" className="flex items-center gap-1 text-[10px] text-[#81916e]">All assessments <ArrowUpRight size={12} /></Link></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="table-head"><th className="rounded-l-md px-3 py-2">Assessment</th><th className="px-3 py-2">Class</th><th className="rounded-r-md px-3 py-2 text-right">Average</th></tr></thead><tbody>{recent.map(a => <tr key={a.id} className="border-b border-[#edf0e8] last:border-0"><td className="py-3.5"><Link to={'/assessments?assessment=' + a.id} className="flex items-center gap-3"><span className="rounded-lg bg-[#f3f5ed] p-2 text-[#8d9a7c]"><BookOpen size={15} /></span><span><span className="text-[11px] font-medium">{a.title}</span><span className="mt-1 block text-[9px] text-[#939c89]">{a.subject} · {a.date}</span></span></Link></td><td className="px-3 text-[10px] text-[#7e8874]">{data.classes.find(c => c.id === a.class_id)?.name}</td><td className="px-3 text-right text-xs font-semibold text-[#658157]">{displayPercent(average(a.scores.map(s => percent(s.score, a.maximum))))}</td></tr>)}</tbody></table>{!recent.length && <p className="py-10 text-center text-xs text-[#909a84]">Your latest assessments will appear here.</p>}</div></section>
 <section className="panel"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-semibold">Next steps, not just numbers</h2><Clock3 size={16} className="text-[#a8ae9d]" /></div>{followups.slice(0, 2).map(i => <Link to={'/interventions?intervention=' + i.id} key={i.id} className="mb-3 block rounded-lg border border-[#e8ebdf] p-3.5"><div className="flex items-center justify-between"><span className="text-[9px] font-medium uppercase tracking-wider text-[#9a8b6e]">Follow-up · {i.review_date || 'Date not set'}</span><ArrowUpRight size={12} className="text-[#9ba78d]" /></div><div className="mt-2 text-[11px] font-medium">{data.students.find(s => s.id === i.student_id)?.name} · {i.subject}</div><p className="mt-1.5 line-clamp-2 text-[10px] leading-relaxed text-[#8d9682]">{i.action}</p></Link>)}{!followups.length && <p className="py-6 text-xs text-[#909a84]">No active follow-ups. Review attention signals to plan support.</p>}<Link to="/attendance" className="mt-3 flex items-center justify-between rounded-lg bg-[#f6f7f0] px-3.5 py-3 text-[10px] text-[#70825f]">A good day starts with showing up.<ArrowRight size={13} /></Link></section></div>;
}