import React, { useState } from 'react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { useSchool } from '@/components/school/SchoolProvider';
import { average, percent } from '@/components/school/intelligence';
export default function PerformanceChart() {
 const { data, school } = useSchool(); const [subject, setSubject] = useState(''); const selected = subject || school.subjects?.[0] || 'Mathematics';
 const filtered = data.assessments.filter(a => a.subject === selected); const dates = [...new Set(filtered.map(a => a.date))].sort();
 const rows = dates.map(date => ({ date: new Date(date + 'T12:00:00').toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }), ...Object.fromEntries(data.classes.map(c => [c.id, average(filtered.filter(a => a.date === date && a.class_id === c.id).flatMap(a => a.scores.map(s => percent(s.score, a.maximum))))])) }));
 const colors = ['#52785b', '#b6c997', '#c3a275', '#9e93b2'];
 return <section className="panel min-w-0"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Learning, in perspective</h2><p className="mt-1 text-[10px] text-[#909789]">Assessment averages by class · not adjusted for difficulty</p></div><select aria-label="Chart subject" className="rounded-md border border-[#e4e8de] bg-white px-2 py-1.5 text-[10px]" value={selected} onChange={e => setSubject(e.target.value)}>{(school.subjects || ['Mathematics']).map(s => <option key={s}>{s}</option>)}</select></div>
 <div className="mt-5 h-[211px]">{rows.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={rows} margin={{ top: 5, right: 6, left: -28, bottom: 0 }}><defs><linearGradient id="learningFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#71946f" stopOpacity={0.15} /><stop offset="100%" stopColor="#71946f" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#edf0e8" strokeDasharray="3 4" vertical={false} /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize: 9, fill: '#939c8b' }} dy={8} /><YAxis domain={[0, 100]} ticks={[0, 25, 50, 75, 100]} tickFormatter={v => v + '%'} axisLine={false} tickLine={false} tick={{ fontSize: 9, fill: '#939c8b' }} /><Tooltip contentStyle={{ borderRadius: 10, border: '1px solid #e5e9df', fontSize: 11 }} formatter={(v, name) => [v + '%', name]} />{data.classes.slice(0, 4).map((c, i) => <Area key={c.id} name={c.name} dataKey={c.id} type="monotone" stroke={colors[i]} strokeWidth={2.2} strokeDasharray={i ? '5 4' : ''} fill={i ? 'transparent' : 'url(#learningFill)'} dot={{ r: 3, fill: colors[i], stroke: 'white', strokeWidth: 2 }} connectNulls />)}</AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-xs text-[#959c90]">Record an assessment to start seeing progress.</div>}</div>
 <div className="mt-4 flex flex-wrap justify-center gap-5">{data.classes.slice(0, 4).map((c, i) => <span key={c.id} className="flex items-center gap-2 text-[10px] text-[#7d8773]"><span style={{ background: colors[i] }} className="h-1.5 w-4 rounded-full" />{c.name}</span>)}</div></section>;
}