import React, { useState } from 'react';
import { Outlet, Link, useLocation } from 'react-router-dom';
import { Menu, ChevronRight, CalendarDays, ShieldCheck, Loader2 } from 'lucide-react';
import { useSchool } from '@/components/school/SchoolProvider';
import Sidebar from '@/components/school/Sidebar';
const labels = { '/': 'Overview', '/students': 'Students', '/classes': 'Classes & subjects', '/attendance': 'Attendance', '/assessments': 'Assessments', '/interventions': 'Interventions', '/reports': 'Reports & insights', '/settings': 'School settings' };
export default function SchoolShell() {
 const [open, setOpen] = useState(false); const { school, isDemo, loading, error } = useSchool(); const { pathname } = useLocation();
 return <div className="min-h-screen bg-[#f7f8f4]"><Sidebar open={open} onClose={() => setOpen(false)} /><div className="lg:ml-[238px] print:ml-0"><header className="flex h-[76px] items-center justify-between gap-3 border-b border-[#e5e9e3] bg-[#fcfdfa] px-5 lg:px-9 print:hidden"><div className="flex items-center gap-3 text-[11px]"><button aria-label="Open navigation" onClick={() => setOpen(true)} className="lg:hidden"><Menu size={20} /></button><span className="hidden text-[#929990] sm:inline">Workspace</span><ChevronRight size={12} className="hidden text-[#a3aaa1] sm:inline" /><span className="font-medium">{labels[pathname]}</span></div><div className="flex items-center gap-4"><span className="hidden items-center gap-2 text-[10px] text-[#7a857a] sm:flex"><CalendarDays size={14} />{school.academic_year} academic year</span><span className="rounded-md border border-[#dfe6da] bg-[#f2f5eb] px-2.5 py-1.5 text-[10px] font-medium text-[#647652]">{school.term}</span><span title="Login-protected workspace" className="border-l pl-4 text-[#6d856a]"><ShieldCheck size={18} /></span></div></header>
 <main className="mx-auto max-w-[1560px] px-5 py-7 md:px-8 lg:px-9">{isDemo && <div className="mb-6 flex flex-wrap items-center justify-between gap-2 rounded-lg border border-[#e4e6d9] bg-[#f0f2e7] px-3.5 py-2 text-[10px] text-[#6f795f] print:hidden"><span><span className="font-semibold">Explore your school’s possibilities.</span> You’re viewing fictional sample data; demo edits last for this session.</span><Link to="/settings" className="font-semibold text-[#385c3e]">Set up your school <span aria-hidden>↗</span></Link></div>}{loading ? <div className="flex justify-center py-32"><Loader2 className="animate-spin" /></div> : error ? <div role="alert" className="panel text-red-700">Unable to load school records. {error.message}</div> : <Outlet key={school.id} />}</main><footer className="mx-9 mt-3 flex flex-wrap justify-between gap-3 border-t border-[#e3e7de] py-5 text-[9px] text-[#9aa293] print:hidden"><span>Thoughtfully built for Zimbabwean schools.</span><span>Observe. Understand. Act. Grow.</span></footer></div></div>;
}