import React from 'react';
import { NavLink } from 'react-router-dom';
import { Sprout, LayoutDashboard, Users, BookOpen, CalendarCheck, ClipboardList, HeartHandshake, ChartNoAxesCombined, Settings2, ArrowUpRight, X, LogOut, ChevronDown } from 'lucide-react';
import { useSchool } from '@/components/school/SchoolProvider';
import { base44 } from '@/api/base44Client';
const items = [{ label: 'Overview', to: '/', icon: LayoutDashboard }, { label: 'Students', to: '/students', icon: Users }, { label: 'Classes & subjects', to: '/classes', icon: BookOpen }, { label: 'Attendance', to: '/attendance', icon: CalendarCheck }, { label: 'Assessments', to: '/assessments', icon: ClipboardList }, { label: 'Interventions', to: '/interventions', icon: HeartHandshake }, { label: 'Reports & insights', to: '/reports', icon: ChartNoAxesCombined }];
export default function Sidebar({ open, onClose }) {
 const { school, schools, setSelected, user, isDemo } = useSchool();
 return <><div onClick={onClose} className={`${open ? 'fixed' : 'hidden'} inset-0 bg-black/30 z-30 lg:hidden`} /><aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 flex w-[238px] flex-col border-r border-[#e5e9e3] bg-[#fcfdfa] transition-transform lg:translate-x-0 print:hidden`}>
 <div className="flex items-center gap-2.5 px-7 pb-8 pt-9"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#254d3c] text-white"><Sprout size={23} strokeWidth={1.6} /></span><span className="font-heading text-[25px] font-extrabold tracking-[-1.2px]">shule<span className="text-[#72987c]">.</span></span><span className="ml-1 mt-1 text-[9px] font-semibold tracking-[.16em] text-[#849087]">SCHOOL OS</span><button aria-label="Close navigation" onClick={onClose} className="ml-auto lg:hidden"><X size={18} /></button></div>
 <div className="mx-5 mb-8 rounded-xl border border-[#e2e7df] bg-white p-3"><div className="flex items-center gap-2.5"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#f0f2e7] font-heading text-xs font-bold">{school.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</div><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-semibold">{school.name}</div><div className="mt-0.5 text-[9px] text-[#89928a]">{school.location || 'Zimbabwe'}</div></div><ChevronDown size={13} /></div>{schools.length > 1 && <select aria-label="Choose school" className="mt-2 w-full bg-transparent text-xs" value={school.id} onChange={e => setSelected(e.target.value)}>{schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select>}</div>
 <div className="px-7 text-[9px] font-semibold tracking-[.17em] text-[#929b93]">WORKSPACE</div><nav className="mt-3 space-y-1 px-4">{items.map(({ label, to, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={onClose} className={({ isActive }) => `flex items-center gap-3 rounded-lg px-3.5 py-3 text-[12px] transition-colors ${isActive ? 'bg-[#e8efe7] font-semibold text-[#31543d]' : 'text-[#737d75] hover:bg-[#f0f3ed]'}`}><Icon size={17} strokeWidth={1.6} />{label}</NavLink>)}</nav>
 <div className="mt-auto px-5 pt-8"><div className="rounded-xl bg-[#f0f3e9] p-4"><Sprout size={20} className="mb-2 text-[#597454]" /><p className="text-xs font-semibold">Every learner. A little further.</p><p className="mt-2 text-[10px] leading-relaxed text-[#7c8775]">Small actions today.<br />Stronger futures tomorrow.</p><NavLink to="/interventions" onClick={onClose} className="mt-3 flex items-center gap-2 text-[10px] font-semibold">View support plans <ArrowUpRight size={13} /></NavLink></div><NavLink to="/settings" onClick={onClose} className="my-4 flex items-center gap-3 px-2 text-xs text-[#737d75]"><Settings2 size={16} /> School settings</NavLink></div>
 <div className="flex items-center gap-2.5 border-t border-[#e5e9e3] p-5"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#e9e5db] text-xs font-semibold">{(user.full_name || user.email || 'A')[0].toUpperCase()}</span><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-semibold">{user.full_name || 'School administrator'}</div><div className="mt-0.5 text-[9px] text-[#8c948b]">{isDemo ? 'Demo workspace' : 'Private school workspace'}</div></div><button title="Sign out" onClick={() => base44.auth.logout('/login')}><LogOut size={15} className="text-[#8c948b]" /></button></div>
 </aside></>;
}