import React from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { Plus, ClipboardList, ArrowUpRight } from 'lucide-react';
import { useSchool } from '@/components/school/SchoolProvider';
import { average, percent, displayPercent } from '@/components/school/intelligence';
import AssessmentForm from '@/components/school/AssessmentForm';
import AssessmentDetail from '@/components/school/AssessmentDetail';
export default function Assessments() {
 const { data } = useSchool(); const [params, setParams] = useSearchParams(); const selected = data.assessments.find(a => a.id === params.get('assessment')); const canRecord = data.students.length > 0;
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="page-title">Record once. Understand more.</h1><p className="page-subtitle">The everyday evidence that makes meaningful progress visible.</p></div><button className="action-primary" disabled={!canRecord} onClick={() => setParams({ new: '1' })}><Plus size={14} />Record marks</button></div>{!canRecord && <div className="panel text-xs">Add a class and its students to record your first assessment. <Link className="underline" to="/students">View students</Link></div>}<section className="panel p-0"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="table-head"><tr>{['Assessment', 'Class', 'Date', 'Results', 'Average', ''].map((h, i) => <th className="p-5" key={i}>{h}</th>)}</tr></thead><tbody>{[...data.assessments].sort((a, b) => b.date.localeCompare(a.date)).map(a => <tr key={a.id} className="border-t border-[#edf0e6] hover:bg-[#fafbf6]"><td className="p-5"><button onClick={() => setParams({ assessment: a.id })} className="flex items-center gap-3 text-left"><span className="rounded-lg bg-[#f0f3e8] p-2.5 text-[#899a73]"><ClipboardList size={18} /></span><span><span className="block text-xs font-medium">{a.title}</span><span className="mt-1 block text-[10px] text-[#919d81]">{a.subject} · {a.topic}</span></span></button></td><td className="p-5 text-[11px] text-[#87947a]">{data.classes.find(c => c.id === a.class_id)?.name}</td><td className="p-5 text-[11px] text-[#87947a]">{a.date}</td><td className="p-5 text-xs">{a.scores.length}</td><td className="p-5 text-xs font-semibold text-[#719056]">{displayPercent(average(a.scores.map(s => percent(s.score, a.maximum))))}</td><td className="p-5"><button aria-label={`View ${a.title}`} onClick={() => setParams({ assessment: a.id })}><ArrowUpRight size={14} /></button></td></tr>)}</tbody></table></div>{!data.assessments.length && <p className="py-20 text-center text-xs text-[#8f9d80]">No assessments yet. Your next learning insight starts with a result.</p>}</section>{params.has('new') && canRecord && <AssessmentForm onClose={() => setParams({})} />}{selected && <AssessmentDetail assessment={selected} onClose={() => setParams({})} />}</div>;
}